import { createContext, useContext, useEffect, useMemo, useState } from "react";

const translations = {
  en: {
    common: {
      home: "Home",
      leaderboard: "Leaderboard",
      profile: "Profile",
      signIn: "Sign in",
      signOut: "Sign out",
      enlist: "Register",
      email: "Email address",
      password: "Password",
      changeEmail: "Change email",
      sendAnotherCode: "Send another code",
      minimumPassword: "Minimum 8 characters",
      hidePassword: "Hide password",
      showPassword: "Show password",
      dismiss: "Dismiss notification",
      username: "Username",
      language: "Language",
      english: "English",
      vietnamese: "Vietnamese",
      loading: "Establishing link",
      admiral: "Admiral",
      admiralClearance: "Admiral clearance",
      accountControls: "Account controls",
      viewProfile: "View profile",
      useDark: "Use dark theme",
      useLight: "Use light theme",
      notifications: "Notifications",
      openAccount: "Open account menu",
    },
    auth: {
      brandSub: "Arena Command Network",
      returnBase: "Return to base",
      backSignIn: "Back to sign in",
      radarLabel: "Fleet network status",
      emailInvalid: "Enter a valid email address.",
      passwordInvalid: "Password must contain at least 8 characters.",
      passwordsMismatch: "Passwords do not match.",
      codeRequired: "Confirmation code is required.",
      resetCodeRequired: "Reset code is required.",
      codePlaceholder: "Enter the code from your email",
      repeatPassword: "Repeat your password",
      repeatNewPassword: "Repeat your new password",
    },
    login: {
      kicker: "Secure channel online",
      title: "Commander access",
      subtitle: "Authenticate to resume command of your fleet.",
      remember: "Keep me signed in",
      recover: "Recover access",
      submit: "Enter command",
      newUser: "New to the command network?",
      create: "Create account",
      accessDenied: "Access denied",
      invalidCredentials: "The email or password does not match our command records.",
      unavailable: "The secure sign-in channel is unavailable. Please try again.",
      passwordUpdated: "Password updated",
      passwordUpdatedBody: "Your command credentials are ready. Sign in with the new password.",
      verified: "Account verified",
      verifiedBody: "Your fleet identity is active. You can now enter command.",
      continueGoogle: "Continue with Google",
      continueFacebook: "Continue with Facebook",
      socialConnecting: "Opening secure channel...",
      orEmail: "or use email",
      socialConfigMissing: "Social sign-in is not configured. Add the Cognito OAuth domain to the environment settings.",
      socialUnavailable: "Social sign-in could not be started. Please try again.",
    },
    register: {
      kicker: "Secure enlistment channel",
      confirmKicker: "Verification channel active",
      title: "Enlist as commander",
      confirmTitle: "Verify your email",
      subtitle: "Create your fleet identity and enter the arena.",
      confirmSubtitle: "Enter the security code sent to {email}.",
      confirmationCode: "Confirmation code",
      confirmCodePlaceholder: "Enter the code from your email",
      confirmPassword: "Confirm password",
      terms: "I accept the service terms",
      termsRequired: "Accept the service terms to continue.",
      submit: "Create account",
      confirmSubmit: "Verify account",
      existing: "Already enlisted?",
      verificationRequired: "Verification required",
      verificationRequiredBody: "Enter the code previously sent to your email to activate this account.",
      codeSent: "Verification code sent",
      codeSentBody: "Check your inbox and spam folder, then enter the six-digit security code.",
      newCode: "New code transmitted",
      newCodeBody: "A fresh verification code has been sent to your email.",
      verifyFailed: "Verification failed",
      enlistFailed: "Enlistment failed",
      accountExists: "An account with this email already exists. Sign in or recover access.",
      policyError: "The password does not meet the Cognito security policy.",
      createError: "Unable to create your fleet identity. Please try again.",
      wrongCode: "The verification code is incorrect.",
      expiredCode: "The verification code has expired. Request a new code.",
      verifyError: "Unable to verify this account. Please try again.",
      resendError: "Unable to resend the verification code.",
    },
    recovery: {
      kicker: "Identity recovery channel",
      title: "Recover access",
      confirmTitle: "Set new password",
      subtitle: "Enter your account email to receive a secure reset code.",
      confirmSubtitle: "Enter the security code sent to {email}.",
      resetCode: "Reset code",
      newPassword: "New password",
      confirmNewPassword: "Confirm new password",
      sendCode: "Send reset code",
      updatePassword: "Update password",
      remembered: "Remembered your password?",
      interrupted: "Recovery interrupted",
      codeSent: "Reset code transmitted",
      codeSentBody: "Check your inbox and spam folder for the password reset code.",
      newCode: "New code transmitted",
      newCodeBody: "A fresh password reset code has been sent to your email.",
      tooMany: "Too many attempts. Wait a moment before requesting another code.",
      sendError: "Unable to send the reset code. Please try again.",
      wrongCode: "The reset code is incorrect.",
      expiredCode: "The reset code has expired. Request a new one.",
      passwordPolicy: "The new password does not meet the Cognito security requirements.",
      resetError: "Unable to reset your password. Please try again.",
      resendError: "Unable to resend the reset code.",
    },
    home: {
      signedInTitle: "Command link established",
      signedInBody: "Signed in successfully. Your fleet profile is now synchronized.",
      signedOutTitle: "Command session closed",
      signedOutBody: "Signed out successfully. Local fleet data remains secured.",
      signOutErrorTitle: "Sign-out interrupted",
      signOutErrorBody: "The secure session could not be closed. Please try again.",
      heroOne: "Command your",
      heroFleet: "fleet.",
      heroTwo: "Outsmart your enemies.",
      learn: "Learn tactics",
      deployment: "Deployment modes",
      bot: "Bot",
      player: "Player",
      room: "Room",
      playBot: "Play vs Bot",
      botBody: "Sharpen your strategic edge against our advanced tactical AI. Choose from Recruit to Elite difficulty levels.",
      aiOpponent: "AI opponent",
      practice: "Practice",
      difficulty: "Select difficulty:",
      easy: "Recruit (Easy)",
      normal: "Veteran (Normal)",
      hard: "Elite (Hard)",
      battle: "Battle now",
      competitive: "Competitive",
      playPlayer: "Play vs Player",
      playerBody: "Match against global commanders in real-time ranked battles. Climb the tiers and claim your glory.",
      matchmaking: "Online matchmaking",
      joinQueue: "Join queue",
      pvpModalKicker: "PvP command channel",
      pvpModalTitle: "Choose battle protocol",
      pvpModalBody: "Select a casual engagement for quick room play, or enter ranked combat with authenticated commander records.",
      casualPvp: "Casual battle",
      casualPvpBody: "Create or join a room without signing in. Results are not counted in ranked records.",
      rankedPvp: "Ranked battle",
      rankedPvpBody: "Requires sign-in. Match results affect commander records and ranking progression.",
      noLoginRequired: "No login required",
      loginRequired: "Sign-in required",
      searchingMatch: "Finding match",
      searchingMatchBody: "Scanning active command channels and preparing a PvP room.",
      scanningCommanders: "Scanning available commanders...",
      cancelSearch: "Cancel search",
      privateRoom: "Private room",
      roomBody: "Host a custom engagement with friends. Share a secure room code and define your own naval rules.",
      customMatch: "Custom match",
      createRoom: "Create room",
      underDevelopment: "This mode is under development.",
      serviceRecord: "Service record",
      topCommanders: "Top commanders",
      topThree: "Top 3 commanders",
      fullLeaderboard: "View full leaderboard",
      rankTier: "Rank tier",
      totalEngagements: "Total engagements",
      victories: "Victories",
      defeats: "Defeats",
      winRate: "Win rate",
      xp: "XP to next rank",
    },
    profile: {
      loading: "Loading commander profile",
      secureAccess: "Secure profile access",
      secureBody: "Sign in to review your commander identity and battle record.",
      commander: "Fleet Commander",
      emailUnavailable: "Email unavailable from social provider",
      operational: "Operational",
      dossier: "Commander dossier",
      cloudFleet: "Cloud fleet",
      deploy: "Deploy fleet",
      serviceRecord: "Service record",
      serviceBody: "Performance synchronized from this device.",
      totalBattles: "Total battles",
      victories: "Victories",
      winRate: "Win rate",
      accuracy: "Accuracy",
      identity: "Identity channel",
      identityBody: "Cognito account status.",
      verification: "Verification",
      verified: "Verified",
      rank: "Rank",
      accountId: "Account ID",
      resetPassword: "Reset password",
      avatarAlt: "Commander profile",
      battleshipIdTitle: "Battleship ID",
      battleshipIdBody: "Your Battleship ID is used by other commanders to search for you in the system.",
      cooldownMessage: "BATTLESHIP ID CAN BE CHANGED EVERY 30 DAYS. YOU WILL BE ABLE TO CHANGE IT AGAIN ON {date}.",
      cooldownMessageJs: "You need to wait {days} more days to change your username.",
      commanderName: "COMMANDER NAME",
      tagline: "TAGLINE",
      checking: "Checking...",
      nameTooShort: "Name must be at least 3 characters",
      tagEmpty: "Tag cannot be empty",
      nameTaken: "Name is already taken",
      nameValid: "Name is valid",
      updateSuccess: "Name changed successfully!",
      updateError: "Error changing name.",
      saveChanges: "SAVE CHANGES",
      unranked: "Unranked",
      commanderLadder: "Commander ladder",
      closeRankLadder: "Close rank ladder",
      pressureGauge: "Pressure gauge",
      rewardManifest: "Reward manifest",
      leagueLevels: "League levels",
      rankedRouteLocked: "Ranked route locked",
      rpSecured: "{points} RP secured",
      rpToRank: "{points} RP to {rank}",
      divisions: "Divisions",
      rankRewardUnlockBronze: "Win ranked battles to unlock Bronze",
      rankRewardEarnRp: "Earn RP from victories",
      rankRewardBeginLadder: "Begin the command ladder",
      rewardBronze1: "Bronze fleet sigil",
      rewardBronze2: "Starter command frame",
      rewardBronze3: "Casual queue access",
      rewardSilver1: "Silver sonar frame",
      rewardSilver2: "Profile signal flare",
      rewardSilver3: "Fleet log accent",
      rewardGold1: "Gold commander border",
      rewardGold2: "Victory banner stripe",
      rewardGold3: "Ranked medal glow",
      rewardPlatinum1: "Platinum hull trim",
      rewardPlatinum2: "Elite avatar ring",
      rewardPlatinum3: "Advanced fleet plate",
      rewardDiamond1: "Diamond war-room aura",
      rewardDiamond2: "Crystal rank wake",
      rewardDiamond3: "High-command title",
      rewardMaster1: "Master command crest",
      rewardMaster2: "Purple reactor flare",
      rewardMaster3: "Prestige battle marker",
      rewardAdmiral1: "Admiral fleet standard",
      rewardAdmiral2: "Gold command beacon",
      rewardAdmiral3: "Legendary profile frame",
      matchHistory: "Match History",
      matchHistoryBody: "Your recent match results.",
      win: "Victory",
      loss: "Defeat",
      room: "Room",
      shots: "Shots",
      misses: "Misses",
      surrendered: "(AFK)",
    },
  },
  vi: {
    common: {
      home: "Trang chủ",
      leaderboard: "Bảng xếp hạng",
      profile: "Hồ sơ",
      signIn: "Đăng nhập",
      signOut: "Đăng xuất",
      enlist: "Đăng ký",
      email: "Địa chỉ email",
      password: "Mật khẩu",
      changeEmail: "Đổi email",
      sendAnotherCode: "Gửi mã khác",
      minimumPassword: "Tối thiểu 8 ký tự",
      hidePassword: "Ẩn mật khẩu",
      showPassword: "Hiện mật khẩu",
      dismiss: "Đóng thông báo",
      username: "Tên người dùng",
      language: "Ngôn ngữ",
      english: "Tiếng Anh",
      vietnamese: "Tiếng Việt",
      loading: "Đang thiết lập kết nối",
      admiral: "Đô đốc",
      admiralClearance: "Quyền truy cập đô đốc",
      accountControls: "Quản lý tài khoản",
      viewProfile: "Xem hồ sơ",
      useDark: "Dùng giao diện tối",
      useLight: "Dùng giao diện sáng",
      notifications: "Thông báo",
      openAccount: "Mở menu tài khoản",
    },
    auth: {
      brandSub: "Mạng lưới chỉ huy đấu trường",
      returnBase: "Về căn cứ",
      backSignIn: "Quay lại đăng nhập",
      radarLabel: "Trạng thái mạng lưới hạm đội",
      emailInvalid: "Vui lòng nhập địa chỉ email hợp lệ.",
      passwordInvalid: "Mật khẩu phải có ít nhất 8 ký tự.",
      passwordsMismatch: "Mật khẩu xác nhận không khớp.",
      codeRequired: "Vui lòng nhập mã xác nhận.",
      resetCodeRequired: "Vui lòng nhập mã đặt lại mật khẩu.",
      codePlaceholder: "Nhập mã trong email",
      repeatPassword: "Nhập lại mật khẩu",
      repeatNewPassword: "Nhập lại mật khẩu mới",
    },
    login: {
      kicker: "Kênh bảo mật đang hoạt động",
      title: "Truy cập chỉ huy",
      subtitle: "Xác thực để tiếp tục điều khiển hạm đội.",
      remember: "Duy trì đăng nhập",
      recover: "Khôi phục truy cập",
      submit: "Vào trung tâm chỉ huy",
      newUser: "Chưa tham gia mạng lưới chỉ huy?",
      create: "Tạo tài khoản",
      accessDenied: "Truy cập bị từ chối",
      invalidCredentials: "Email hoặc mật khẩu không khớp với dữ liệu chỉ huy.",
      unavailable: "Kênh đăng nhập bảo mật đang gián đoạn. Vui lòng thử lại.",
      passwordUpdated: "Đã cập nhật mật khẩu",
      passwordUpdatedBody: "Thông tin đăng nhập đã sẵn sàng. Hãy đăng nhập bằng mật khẩu mới.",
      verified: "Đã xác minh tài khoản",
      verifiedBody: "Danh tính hạm đội đã hoạt động. Bạn có thể vào trung tâm chỉ huy.",
      continueGoogle: "Tiếp tục với Google",
      continueFacebook: "Tiếp tục với Facebook",
      socialConnecting: "Đang mở kênh bảo mật...",
      orEmail: "hoặc dùng email",
      socialConfigMissing: "Đăng nhập liên kết chưa được cấu hình. Hãy thêm domain OAuth Cognito vào biến môi trường.",
      socialUnavailable: "Không thể bắt đầu đăng nhập liên kết. Vui lòng thử lại.",
    },
    register: {
      kicker: "Kênh đăng ký bảo mật",
      confirmKicker: "Kênh xác minh đang hoạt động",
      title: "Đăng ký làm chỉ huy",
      confirmTitle: "Xác minh email",
      subtitle: "Tạo danh tính hạm đội và bước vào đấu trường.",
      confirmSubtitle: "Nhập mã bảo mật đã gửi đến {email}.",
      confirmationCode: "Mã xác nhận",
      confirmCodePlaceholder: "Nhập mã trong email",
      confirmPassword: "Xác nhận mật khẩu",
      terms: "Tôi đồng ý với điều khoản dịch vụ",
      termsRequired: "Bạn cần đồng ý điều khoản dịch vụ để tiếp tục.",
      submit: "Tạo tài khoản",
      confirmSubmit: "Xác minh tài khoản",
      existing: "Đã có tài khoản?",
      verificationRequired: "Cần xác minh",
      verificationRequiredBody: "Nhập mã đã được gửi đến email để kích hoạt tài khoản.",
      codeSent: "Đã gửi mã xác minh",
      codeSentBody: "Kiểm tra hộp thư đến và thư rác, sau đó nhập mã bảo mật sáu chữ số.",
      newCode: "Đã gửi mã mới",
      newCodeBody: "Mã xác minh mới đã được gửi đến email.",
      verifyFailed: "Xác minh thất bại",
      enlistFailed: "Đăng ký thất bại",
      accountExists: "Email này đã có tài khoản. Hãy đăng nhập hoặc khôi phục truy cập.",
      policyError: "Mật khẩu chưa đáp ứng chính sách bảo mật Cognito.",
      createError: "Không thể tạo danh tính hạm đội. Vui lòng thử lại.",
      wrongCode: "Mã xác minh không chính xác.",
      expiredCode: "Mã xác minh đã hết hạn. Hãy yêu cầu mã mới.",
      verifyError: "Không thể xác minh tài khoản. Vui lòng thử lại.",
      resendError: "Không thể gửi lại mã xác minh.",
    },
    recovery: {
      kicker: "Kênh khôi phục danh tính",
      title: "Khôi phục truy cập",
      confirmTitle: "Đặt mật khẩu mới",
      subtitle: "Nhập email tài khoản để nhận mã đặt lại bảo mật.",
      confirmSubtitle: "Nhập mã bảo mật đã gửi đến {email}.",
      resetCode: "Mã đặt lại",
      newPassword: "Mật khẩu mới",
      confirmNewPassword: "Xác nhận mật khẩu mới",
      sendCode: "Gửi mã đặt lại",
      updatePassword: "Cập nhật mật khẩu",
      remembered: "Đã nhớ mật khẩu?",
      interrupted: "Khôi phục bị gián đoạn",
      codeSent: "Đã gửi mã đặt lại",
      codeSentBody: "Kiểm tra hộp thư đến và thư rác để lấy mã đặt lại mật khẩu.",
      newCode: "Đã gửi mã mới",
      newCodeBody: "Mã đặt lại mật khẩu mới đã được gửi đến email.",
      tooMany: "Có quá nhiều lần thử. Hãy chờ một lúc trước khi yêu cầu mã mới.",
      sendError: "Không thể gửi mã đặt lại. Vui lòng thử lại.",
      wrongCode: "Mã đặt lại không chính xác.",
      expiredCode: "Mã đặt lại đã hết hạn. Hãy yêu cầu mã mới.",
      passwordPolicy: "Mật khẩu mới chưa đáp ứng yêu cầu bảo mật Cognito.",
      resetError: "Không thể đặt lại mật khẩu. Vui lòng thử lại.",
      resendError: "Không thể gửi lại mã đặt lại.",
    },
    home: {
      signedInTitle: "Đã thiết lập liên kết chỉ huy",
      signedInBody: "Đăng nhập thành công. Hồ sơ hạm đội đã được đồng bộ.",
      signedOutTitle: "Đã đóng phiên chỉ huy",
      signedOutBody: "Đăng xuất thành công. Dữ liệu hạm đội cục bộ vẫn được bảo vệ.",
      signOutErrorTitle: "Đăng xuất bị gián đoạn",
      signOutErrorBody: "Không thể đóng phiên bảo mật. Vui lòng thử lại.",
      heroOne: "Chỉ huy",
      heroFleet: "hạm đội.",
      heroTwo: "Đánh bại mọi đối thủ.",
      learn: "Học chiến thuật",
      deployment: "Chế độ triển khai",
      bot: "Máy",
      player: "Người chơi",
      room: "Phòng",
      playBot: "Đấu với máy",
      botBody: "Rèn luyện chiến thuật trước AI tác chiến. Chọn cấp độ từ Tân binh đến Tinh nhuệ.",
      aiOpponent: "Đối thủ AI",
      practice: "Luyện tập",
      difficulty: "Chọn độ khó:",
      easy: "Tân binh (Dễ)",
      normal: "Cựu binh (Thường)",
      hard: "Tinh nhuệ (Khó)",
      battle: "Vào trận",
      competitive: "Xếp hạng",
      playPlayer: "Đấu với người chơi",
      playerBody: "Đối đầu các chỉ huy toàn cầu trong trận xếp hạng thời gian thực.",
      matchmaking: "Ghép trận trực tuyến",
      joinQueue: "Tham gia hàng chờ",
      pvpModalKicker: "Kênh chỉ huy PvP",
      pvpModalTitle: "Chọn giao thức chiến đấu",
      pvpModalBody: "Chọn đấu thường để vào phòng nhanh, hoặc đấu rank với hồ sơ chỉ huy đã xác thực.",
      casualPvp: "Đấu thường",
      casualPvpBody: "Tạo hoặc vào phòng mà không cần đăng nhập. Kết quả không tính vào hồ sơ xếp hạng.",
      rankedPvp: "Đấu rank",
      rankedPvpBody: "Yêu cầu đăng nhập. Kết quả trận sẽ ảnh hưởng hồ sơ và tiến trình xếp hạng.",
      noLoginRequired: "Không cần đăng nhập",
      loginRequired: "Cần đăng nhập",
      searchingMatch: "Đang tìm trận",
      searchingMatchBody: "Đang quét các kênh chỉ huy hoạt động và chuẩn bị phòng PvP.",
      scanningCommanders: "Đang quét chỉ huy khả dụng...",
      cancelSearch: "Hủy tìm trận",
      privateRoom: "Phòng riêng",
      roomBody: "Tạo trận tùy chỉnh cùng bạn bè, chia sẻ mã phòng bảo mật và thiết lập luật chơi.",
      customMatch: "Trận tùy chỉnh",
      createRoom: "Tạo phòng",
      underDevelopment: "Chế độ này đang được phát triển.",
      serviceRecord: "Hồ sơ chiến đấu",
      topCommanders: "Chỉ huy hàng đầu",
      topThree: "Top 3 chỉ huy",
      fullLeaderboard: "Xem toàn bộ bảng xếp hạng",
      rankTier: "Cấp bậc",
      totalEngagements: "Tổng trận",
      victories: "Chiến thắng",
      defeats: "Thất bại",
      winRate: "Tỷ lệ thắng",
      xp: "XP đến cấp tiếp theo",
    },
    profile: {
      loading: "Đang tải hồ sơ chỉ huy",
      secureAccess: "Truy cập hồ sơ bảo mật",
      secureBody: "Đăng nhập để xem danh tính chỉ huy và hồ sơ chiến đấu.",
      commander: "Chỉ huy hạm đội",
      emailUnavailable: "Nhà cung cấp liên kết không trả về email",
      operational: "Đang hoạt động",
      dossier: "Hồ sơ chỉ huy",
      cloudFleet: "Hạm đội đám mây",
      deploy: "Triển khai hạm đội",
      serviceRecord: "Hồ sơ chiến đấu",
      serviceBody: "Hiệu suất được đồng bộ từ thiết bị này.",
      totalBattles: "Tổng trận",
      victories: "Chiến thắng",
      winRate: "Tỷ lệ thắng",
      accuracy: "Độ chính xác",
      identity: "Kênh danh tính",
      identityBody: "Trạng thái tài khoản Cognito.",
      verification: "Xác minh",
      verified: "Đã xác minh",
      rank: "Cấp bậc",
      accountId: "Mã tài khoản",
      resetPassword: "Đặt lại mật khẩu",
      avatarAlt: "Hồ sơ chỉ huy",
      battleshipIdTitle: "Battleship ID",
      battleshipIdBody: "Battleship ID của bạn được các chỉ huy khác sử dụng để tìm kiếm bạn trong hệ thống.",
      cooldownMessage: "BATTLESHIP ID CÓ THỂ ĐƯỢC THAY ĐỔI MỖI 30 NGÀY. BẠN SẼ CÓ THỂ THAY ĐỔI LẠI VÀO NGÀY {date}.",
      cooldownMessageJs: "Bạn cần chờ {days} ngày nữa để đổi tên.",
      commanderName: "TÊN CHỈ HUY",
      tagline: "TAGLINE",
      checking: "Đang kiểm tra...",
      nameTooShort: "Tên phải có ít nhất 3 ký tự",
      tagEmpty: "Tag không được để trống",
      nameTaken: "Tên đã bị trùng",
      nameValid: "Tên hợp lệ",
      updateSuccess: "Đổi tên thành công!",
      updateError: "Lỗi khi đổi tên.",
      saveChanges: "LƯU THAY ĐỔI",
      unranked: "Chưa xếp hạng",
      commanderLadder: "Thang cấp chỉ huy",
      closeRankLadder: "Đóng thang rank",
      pressureGauge: "Ống áp suất",
      rewardManifest: "Phần thưởng",
      leagueLevels: "Các bậc rank",
      rankedRouteLocked: "Lộ trình rank đang khóa",
      rpSecured: "{points} RP đã đạt",
      rpToRank: "{points} RP đến {rank}",
      divisions: "Hạng đấu",
      rankRewardUnlockBronze: "Đấu rank để mở khóa Đồng",
      rankRewardEarnRp: "Nhận RP từ chiến thắng",
      rankRewardBeginLadder: "Bắt đầu lộ trình chỉ huy",
      rewardBronze1: "Huy hiệu hạm đội Đồng",
      rewardBronze2: "Khung chỉ huy khởi đầu",
      rewardBronze3: "Mở hàng chờ thường",
      rewardSilver1: "Khung sonar Bạc",
      rewardSilver2: "Tín hiệu hồ sơ",
      rewardSilver3: "Nhấn mạnh nhật ký hạm đội",
      rewardGold1: "Viền chỉ huy Vàng",
      rewardGold2: "Dải băng chiến thắng",
      rewardGold3: "Hào quang huy chương rank",
      rewardPlatinum1: "Viền thân tàu Bạch kim",
      rewardPlatinum2: "Vòng avatar tinh nhuệ",
      rewardPlatinum3: "Bảng hạm đội nâng cao",
      rewardDiamond1: "Hào quang phòng chiến Kim cương",
      rewardDiamond2: "Vệt sóng pha lê",
      rewardDiamond3: "Danh hiệu bộ chỉ huy cao",
      rewardMaster1: "Huy hiệu Cao thủ",
      rewardMaster2: "Luồng sáng lò phản ứng tím",
      rewardMaster3: "Dấu hiệu uy danh",
      rewardAdmiral1: "Chuẩn hạm đội Đô đốc",
      rewardAdmiral2: "Đèn hiệu lệnh vàng",
      rewardAdmiral3: "Khung hồ sơ huyền thoại",
      matchHistory: "Lịch sử trận đấu",
      matchHistoryBody: "Kết quả các trận đấu gần đây của bạn.",
      win: "Thắng",
      loss: "Thua",
      room: "Phòng",
      shots: "Đã bắn",
      misses: "Trượt",
      surrendered: "(AFK)",
    },
  },
};

const LanguageContext = createContext(null);

function resolveTranslation(language, key, values = {}) {
  const value = key.split(".").reduce((current, part) => current?.[part], translations[language]);
  const fallback = key.split(".").reduce((current, part) => current?.[part], translations.en);
  const text = value || fallback || key;

  return Object.entries(values).reduce(
    (result, [name, replacement]) => result.replaceAll(`{${name}}`, replacement),
    text,
  );
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem("battleshipLanguage") || "en");

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage(nextLanguage) {
      if (nextLanguage === language) return;

      localStorage.setItem("battleshipLanguage", nextLanguage);
      document.documentElement.lang = nextLanguage;
      setLanguageState(nextLanguage);
    },
    t(key, values) {
      return resolveTranslation(language, key, values);
    },
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

// The hook intentionally shares this module with its provider.
// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  return useContext(LanguageContext);
}
